In [1]:
%run imports_and_functions.ipynb

C:\Users\Jason\AppData\Local\conda\conda\envs\DSI-6\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Constructing All Cities Dataset

In [2]:
trainrowcoords = pd.read_csv('LasVegasTrainRowCoords.csv',sep=';',compression='gzip')
trainrowcoords = trainrowcoords.set_index('Unnamed: 0')
trainrowcoords.index.name = 'geoid'
trainrowcoords.head()

distance urban   latitude   longitude    blockgroup  \
geoid                                                                     
320030029581005  5403.219921     U  36.093640 -115.241871  320030029581   
320030029572000  5808.613932     U  36.096091 -115.248927  320030029572   
320030010042004  3855.731439     U  36.155052 -115.198804  320030010042   
320030010031016  4532.868829     U  36.154625 -115.220151  320030010031   
320030029381020  3136.357472     U  36.137785 -115.219814  320030029381   

                 income  blockgrouppop  population  landarea  waterarea  block  
geoid                                                                           
320030029581005   25757           1495         155     54924          0   1005  
320030029572000   52256            884         437    728659          0   2000  
320030010042004   25408           1249          32     17103          0   2004  
320030010031016   24759           1058          29     41920          0   1016  
320030029381020   34314           1539          35     39561          0   1020

In [19]:
y_train = joblib.load('y_trainLasVegas.joblib')

In [20]:
y_train.shape

(1784,)

In [21]:
X_train = joblib.load('X_trainLasVegas.joblib')
X_train.shape

(1784, 1482)

In [22]:
X_train2 = joblib.load('X_trainPhoenix.joblib')
y_train2 = joblib.load('y_trainPhoenix.joblib')

X_train3 = joblib.load('X_trainCharlotte.joblib')
y_train3 = joblib.load('y_trainCharlotte.joblib')

X_train4 = joblib.load('X_trainPittsburgh.joblib')
y_train4 = joblib.load('y_trainPittsburgh.joblib')

In [23]:
print(X_train.shape, X_train2.shape, X_train3.shape, X_train4.shape)

(1784, 1482) (3349, 1482) (2739, 1482) (3297, 1482)


In [24]:
X_allcities = X_train.append(X_train2).append(X_train3).append(X_train4)

In [25]:
y_allcities = y_train.append(y_train2).append(y_train3).append(y_train4)
y_allcities.shape

(11169,)

In [38]:
X_allcities.index = y_allcities.index
X_allcities.head()

landarea  waterarea  0_restaurants_near  0_restaurants_far  \
320030029581005         0          0                   0                  1   
320030029572000         0          0                   0                  1   
320030010042004         0          0                   0                  3   
320030010031016         0          0                   0                  2   
320030029381020         0          0                   0                 35   

                 1_restaurants_near  1_restaurants_far  2_restaurants_near  \
320030029581005                   8                 37                   4   
320030029572000                   0                 31                   0   
320030010042004                   3                 22                   3   
320030010031016                   0                 22                   1   
320030029381020                   0                 71                   0   

                 2_restaurants_far  3_restaurants_near  3_restaurants_far  \
320030029581005                 26                   0                  0   
320030029572000                 22                   0                  0   
320030010042004                 16                   0                  0   
320030010031016                 12                   0                  8   
320030029381020                 11                   0                  3   

                 4_restaurants_near  4_restaurants_far  0_shopping_near  \
320030029581005                   0                  0                0   
320030029572000                   0                  0                0   
320030010042004                   0                  0                4   
320030010031016                   0                  0                0   
320030029381020                   0                  0                0   

                 0_shopping_far  1_shopping_near  1_shopping_far  \
320030029581005               4                0              27   
320030029572000               3                0              17   
320030010042004              12                4              17   
320030010031016              12                0              14   
320030029381020              42                0               2   

                 2_shopping_near  2_shopping_far  3_shopping_near  \
320030029581005                4               6                2   
320030029572000                0               5                0   
320030010042004               10              38                1   
320030010031016                0              13                0   
320030029381020                1              99                0   

                 3_shopping_far  4_shopping_near  4_shopping_far  0_food_near  \
320030029581005               0                0               0            0   
320030029572000               2                0               0            0   
320030010042004               6                0               0            0   
320030010031016               4                0               2            2   
320030029381020               1                0               0            0   

                 0_food_far  1_food_near  1_food_far  2_food_near  2_food_far  \
320030029581005           0            4          19            3           7   
320030029572000           0            0           7            0           7   
320030010042004           3            5          14            2           1   
320030010031016           2            0           4            1          10   
320030029381020          32            0         100            0          34   

                 3_food_near  3_food_far  4_food_near  4_food_far  \
320030029581005            0           0            0           0   
320030029572000            0           0            0           0   
320030010042004            0           2            0           0   
320030010031016            0           4            0           0   
320030029381020 

In [35]:
rowstodrop = y_allcities[y_allcities == '-'].index

In [39]:
print(X_allcities.shape)
X_allcities.drop(rowstodrop, axis=0, inplace=True)
X_allcities.shape

(11169, 1482)


(11153, 1482)

In [40]:
print(y_allcities.shape)
y_allcities.drop(rowstodrop, axis=0, inplace=True)
y_allcities.shape

(11169,)


(11153,)

In [49]:
nantodrop = y_allcities[y_allcities.isna()].index
print(X_allcities.shape)
X_allcities.drop(nantodrop, axis=0, inplace=True)
X_allcities.shape

(11153, 1482)


(11126, 1482)

In [50]:
print(y_allcities.shape)
y_allcities.drop(nantodrop, axis=0, inplace=True)
y_allcities.shape

(11153,)


(11126,)

In [5]:
y_allcities = y_allcities.map(float)

y_allcities.head()

320030029581005    25757.0
320030029572000    52256.0
320030010042004    25408.0
320030010031016    24759.0
320030029381020    34314.0
Name: income, dtype: float64

In [53]:
joblib.dump(X_allcities, 'Xtrain_allcities.joblib', compress=9)

['Xtrain_allcities.joblib']

In [6]:
joblib.dump(y_allcities, 'ytrain_allcities.joblib', compress=9)

['ytrain_allcities.joblib']

## Testing Varied ML Models on All Cities Dataset

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, AdaBoostRegressor, RandomForestRegressor, BaggingClassifier
from sklearn.svm import SVR
from sklearn.metrics import f1_score, mean_squared_error

In [3]:
X_allcities = joblib.load('Xtrain_allcities.joblib')
y_allcities = joblib.load('ytrain_allcities.joblib')

In [4]:
def accuracy_scorer(model, X_train, X_test, y_train, y_test):
    
    y_pred = pd.Series(data=model.predict(X_train),dtype=int)
    accuracy_train = f1_score(y_true = y_train,
                        y_pred = y_pred, average=None)
    
    y_pred = pd.Series(data=model.predict(X_test),dtype=int)
    accuracy_test = f1_score(y_true = y_test,
                       y_pred = y_pred, average=None)
    
    r2_scores = (model.score(X_train, y_train), model.score(X_test, y_test))
    
    print("R2 scores for " + str(type(model)) + " train set: " + str(r2_scores[0]))
    print("R2 scores for " + str(type(model)) + " test set: " + str(r2_scores[1]))
    print("The training accuracy-score for " + str(type(model)) + " is: ")
    print(str(accuracy_train))
    print("The testing accuracy-score for " + str(type(model)) + " is: ")
    print(str(accuracy_test))
    print()
    return (accuracy_train, accuracy_test)

### Preliminary Regressions (income still continuous)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_allcities, 
                                                    test_size=.15, random_state=42) 
X_train.shape

(9457, 1482)

In [62]:

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA()
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [ ]:
linear_reg_PCA = LinearRegression()
linear_reg_PCA.fit(Z_train, y_train)

knn_reg_PCA = KNeighborsRegressor()
knn_reg_PCA.fit(Z_train, y_train)

cart_reg_PCA = DecisionTreeRegressor()
cart_reg_PCA.fit(Z_train, y_train)

In [63]:
bagged_reg_PCA = BaggingRegressor()
bagged_reg_PCA.fit(Z_train, y_train)

adaboost_reg_PCA = AdaBoostRegressor()
adaboost_reg_PCA.fit(Z_train, y_train)

random_forest_reg_PCA = RandomForestRegressor()
random_forest_reg_PCA.fit(Z_train, y_train)

AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
         n_estimators=50, random_state=None)

In [66]:
support_vector_reg_PCA = SVR()
support_vector_reg_PCA.fit(Z_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [67]:
pca_reg_models = [linear_reg_PCA, knn_reg_PCA, cart_reg_PCA, bagged_reg_PCA, 
              adaboost_reg_PCA, random_forest_reg_PCA, support_vector_reg_PCA]

In [69]:
def rmse_scorer(model, X_train, X_test, y_train, y_test):
    mse_train = mean_squared_error(y_true = y_train,
                                  y_pred = model.predict(X_train))
    mse_test = mean_squared_error(y_true = y_test,
                                  y_pred = model.predict(X_test))
    rmse_train = mse_train ** 0.5
    rmse_test = mse_test ** 0.5

    r2_scores = (model.score(X_train, y_train), model.score(X_test, y_test))
    
    print("R2 scores for " + str(type(model)) + " train set: " + str(r2_scores[0]))
    print("R2 scores for " + str(type(model)) + " test set: " + str(r2_scores[1]))
    print("The training RMSE for " + str(type(model)) + " is: ")
    print(str(rmse_train))
    print("The testing RMSE for " + str(type(model)) + " is: ")
    print(str(rmse_test))
    print()
    return (rmse_train, rmse_test)

In [70]:
for model in pca_reg_models :
    rmse_scorer(model, Z_train, Z_test, y_train, y_test)
# KNN has good scores but takes orders of magnitude time longer (10+ minutes) so shouldn't
# implement for user side functionality
# SVM is also pretty long, and has the worst scores

R2 scores for <class 'sklearn.linear_model.base.LinearRegression'> train set: 0.7998428809318361
R2 scores for <class 'sklearn.linear_model.base.LinearRegression'> test set: -2.1657883903251046e+23
The training RMSE for <class 'sklearn.linear_model.base.LinearRegression'> is: 
10388.948010809852
The testing RMSE for <class 'sklearn.linear_model.base.LinearRegression'> is: 
1.0169723572506662e+16

R2 scores for <class 'sklearn.neighbors.regression.KNeighborsRegressor'> train set: 0.8791982969879253
R2 scores for <class 'sklearn.neighbors.regression.KNeighborsRegressor'> test set: 0.8440173262915125
The training RMSE for <class 'sklearn.neighbors.regression.KNeighborsRegressor'> is: 
8070.911415906978
The testing RMSE for <class 'sklearn.neighbors.regression.KNeighborsRegressor'> is: 
8630.56679047727

R2 scores for <class 'sklearn.tree.tree.DecisionTreeRegressor'> train set: 0.9621831940443599
R2 scores for <class 'sklearn.tree.tree.DecisionTreeRegressor'> test set: 0.5686861683209876
T

In [74]:
# Testing better models with PCA number of columns set to best 200 (out of 1482)
bagged_reg_PCA = BaggingRegressor()
bagged_reg_PCA.fit(Z_train, y_train)

adaboost_reg_PCA = AdaBoostRegressor()
adaboost_reg_PCA.fit(Z_train, y_train)

random_forest_reg_PCA = RandomForestRegressor()
random_forest_reg_PCA.fit(Z_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [75]:
for model in [bagged_reg_PCA, adaboost_reg_PCA, random_forest_reg_PCA] :
    rmse_scorer(model, Z_train, Z_test, y_train, y_test)
# restricting to top 200 variables of PCA axis rotation only improves r2 scores by about 1 percent here

R2 scores for <class 'sklearn.ensemble.bagging.BaggingRegressor'> train set: 0.931418388037298
R2 scores for <class 'sklearn.ensemble.bagging.BaggingRegressor'> test set: 0.7596213917622368
The training RMSE for <class 'sklearn.ensemble.bagging.BaggingRegressor'> is: 
0.24040429478189504
The testing RMSE for <class 'sklearn.ensemble.bagging.BaggingRegressor'> is: 
0.4284549107959935

R2 scores for <class 'sklearn.ensemble.weight_boosting.AdaBoostRegressor'> train set: 0.3431086962397566
R2 scores for <class 'sklearn.ensemble.weight_boosting.AdaBoostRegressor'> test set: 0.29172781641549006
The training RMSE for <class 'sklearn.ensemble.weight_boosting.AdaBoostRegressor'> is: 
0.7440208975927295
The testing RMSE for <class 'sklearn.ensemble.weight_boosting.AdaBoostRegressor'> is: 
0.7354570402582684

R2 scores for <class 'sklearn.ensemble.forest.RandomForestRegressor'> train set: 0.9305483221778924
R2 scores for <class 'sklearn.ensemble.forest.RandomForestRegressor'> test set: 0.7683522

### Testing 7 brackets of Income (0-11k, 11-21k, 21-31k, 31-41k, 41-51k, 51k-61k, 61k+)

In [7]:
print(y_allcities[y_allcities < 11000].shape)
print(y_allcities[(y_allcities >= 11000) & (y_allcities < 21000)].shape)
print(y_allcities[(y_allcities >= 21000) & (y_allcities < 31000)].shape)
print(y_allcities[(y_allcities >= 31000) & (y_allcities < 41000)].shape)
print(y_allcities[(y_allcities >= 41000) & (y_allcities < 51000)].shape)
print(y_allcities[(y_allcities >= 51000) & (y_allcities < 61000)].shape)
print(y_allcities[y_allcities >= 61000].shape)

(3655,)
(2385,)
(2164,)
(1067,)
(641,)
(419,)
(795,)


In [8]:
## Creating column y_train_class

y_train = y_allcities

y_train_class = pd.Series(['NaN' for i in range(len(y_train)) ])

## Creating y_train for classification

brackets ={'$0-$10.99k': 0,'$11-$20.99k':1, '$21-$30.99k':2, '$31-$40.99k':3, '$41-$50.99k':54, 
           '$51-$60.99k':5,'$61-$70.99k':6, '$71+k':7}

for index, value in enumerate(y_train):
    if y_train.iloc[index] < 11000:
        y_train_class.iloc[index] = brackets['$0-$10.99k']
    elif y_train.iloc[index] < 21000:
        y_train_class.iloc[index] = brackets['$11-$20.99k']
    elif y_train.iloc[index] < 31000:
        y_train_class.iloc[index] = brackets['$21-$30.99k']
    elif y_train.iloc[index] < 41000:
        y_train_class.iloc[index] = brackets['$31-$40.99k']   
    elif y_train.iloc[index] < 51000:
        y_train_class.iloc[index] = brackets['$41-$50.99k']
    elif y_train.iloc[index] < 61000:
        y_train_class.iloc[index] = brackets['$51-$60.99k']
    elif y_train.iloc[index] < 71000:
        y_train_class.iloc[index] = brackets['$61-$70.99k']   
    elif y_train.iloc[index] >= 71000:
        y_train_class.iloc[index] = brackets['$71+k']
    else:
        y_train_class.iloc[index] = np.nan

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class, 
                                                    test_size=.15, random_state=42) 
X_train.shape

(9457, 1482)

#### Logistic and Random Forest without PCA to get Theoretical Feature Importances

In [10]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(X_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [11]:
for model in [logreg_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, X_train, X_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.8132600190335202
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7717195925704015
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92312661 0.76304156 0.71416781 0.63925729 0.90576653 0.94033413
 0.89384289 0.78738555]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.91620112 0.71658986 0.68661417 0.56818182 0.84126984 0.69090909
 0.765625   0.75531915]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.9556941947763561
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.8466147393648892
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.96927651 0.9094236  0.9557423  0.96645821 0.99152542 0.99530516
 0.98031088 0.98867925]
The testing accuracy-score for <cla

In [12]:
joblib.dump(logreg_class_pca, 'log_No_pca_8brackets_1stcities.joblib', compress=9)

joblib.dump(random_forest_class_pca, 'rf_No_pca_8brackets_1stcities.joblib', compress=9)

['rf_No_pca_8brackets_1stcities.joblib']

In [17]:
len(logreg_class_pca.coef_[0])

1482

In [20]:
random_forest_class_pca.feature_importances_

array([0.        , 0.        , 0.00210959, ..., 0.        , 0.        ,
       0.        ])

In [73]:

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [77]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [78]:
knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [79]:
cart_class_pca = DecisionTreeClassifier()
cart_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [80]:
random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

adaboost_class_pca = AdaBoostClassifier()
adaboost_class_pca.fit(Z_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [8]:
# from sklearn.svm import SVC

# support_vector_class_pca = SVC()
# support_vector_class_pca.fit(Z_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
for model in [logreg_class_pca, random_forest_class_pca, adaboost_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)
# AdaBoost is the worst classifier among those tested, with default parameters, and
# with this level of income brackets

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.9050438828381093
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.8376273217495507
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: [0.96134787 0.84821429 0.86104149 0.87700535 0.94524496 0.95421687
 0.95010395 0.93140097]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: [0.9417383  0.82420091 0.78373984 0.70588235 0.816      0.79245283
 0.79069767 0.76470588]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.9548482605477424
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.7681246255242661
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: [0.96831683 0.90838474 0.95457095 0.96587031 0.99004267 0.99297424
 0.98343685 0.98770104]
The testing accuracy-score for <class 

In [ ]:
joblib.dump(logreg_class_pca, 'log_pca_8brackets.joblib', compress=9)

joblib.dump(random_forest_class_pca, 'rf_pca_8brackets.joblib', compress=9)

In [13]:
for model in [cart_class_pca, bagged_class_pca, support_vector_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)
# SVC is not that good, scoring wise and takes orders of magnitude more time to run

R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> train set: 0.9579147721264671
R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> test set: 0.6878370281605752
The training accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: [0.96959683 0.91054679 0.95908072 0.97107204 0.99575672 0.99765808
 0.98655636 0.99338999]
The testing accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: [0.8213228  0.71544715 0.67298578 0.53896104 0.453125   0.2962963
 0.47058824 0.57560976]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train set: 0.9532621338690916
R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> test set: 0.7902935889754344
The training accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: [0.96815707 0.90830094 0.95328671 0.96177981 0.98011364 0.9882904
 0.9761163  0.98676749]
The testing accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> 

In [15]:
accuracy_scorer(knn_class_pca, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.848260547742413
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.7890952666267226
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.90238548 0.80592105 0.84248475 0.77426901 0.80225989 0.8
 0.86508754 0.81695568]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.88519135 0.73537604 0.75974026 0.67114094 0.72440945 0.73076923
 0.8125     0.7106599 ]



(array([0.90238548, 0.80592105, 0.84248475, 0.77426901, 0.80225989,
        0.8       , 0.86508754, 0.81695568]),
 array([0.88519135, 0.73537604, 0.75974026, 0.67114094, 0.72440945,
        0.73076923, 0.8125    , 0.7106599 ]))

### Testing 4 brackets of Income (0-20k, 20-40k, 40k-60k, 61k+)

In [5]:
print(y_allcities[y_allcities < 20000].shape)
print(y_allcities[(y_allcities >= 20000) & (y_allcities < 40000)].shape)
print(y_allcities[(y_allcities >= 40000) & (y_allcities < 60000)].shape)
print(y_allcities[y_allcities >= 60000].shape)

(5774,)
(3448,)
(1080,)
(824,)


In [6]:
## Creating column y_train_class2

y_train = y_allcities

y_train_class2 = pd.Series(['NaN' for i in range(len(y_train)) ])

## Creating y_train for classification

brackets ={'$0-$20.99k': 0,'$21-$40.99k':1, '$41-$60.99k':2, '$61+k':3}

for index, value in enumerate(y_train):
    if y_train.iloc[index] < 21000:
        y_train_class2.iloc[index] = brackets['$0-$20.99k']
    elif y_train.iloc[index] < 41000:
        y_train_class2.iloc[index] = brackets['$21-$40.99k']
    elif y_train.iloc[index] < 61000:
        y_train_class2.iloc[index] = brackets['$41-$60.99k']
    elif y_train.iloc[index] >= 61000:
        y_train_class2.iloc[index] = brackets['$61+k']
    else:
        y_train_class2.iloc[index] = np.nan

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class2, 
                                                    test_size=.15, random_state=42) 
X_train.shape

(9457, 1482)

In [9]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(X_train, y_train)

knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(X_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(X_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [11]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, X_train, X_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.8822036586655387
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.8478130617136009
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92168562 0.81661562 0.81957187 0.89841986]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.90309278 0.76600442 0.76677316 0.80446927]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9140319340171301
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.8753744757339724
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.9462201  0.8764255  0.85353245 0.8922853 ]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.92864638 0.82034632 0.77675841 0.77348066]

R2

In [12]:
X_allcities.sum().shape

(1482,)

In [13]:
joblib.dump(X_allcities.sum(), '1stcities_category_counts.joblib', compress=9)

joblib.dump(logreg_class_pca, 'log_No_pca_4brackets_1stcities.joblib', compress=9)

joblib.dump(random_forest_class_pca, 'rf_No_pca_4brackets_1stcities.joblib', compress=9)

['rf_No_pca_4brackets_1stcities.joblib']

In [21]:
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

(9457, 1482)

In [8]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

adaboost_class_pca = AdaBoostClassifier()
adaboost_class_pca.fit(Z_train, y_train)

NameError: name 'Z_train' is not defined

In [85]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca, 
              adaboost_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7387120651369357
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7243858597962852
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.82445657 0.55809935 0.61528059 0.76152623]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.82415459 0.5403423  0.56115108 0.6627907 ]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9078989108596807
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.8669862192929898
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.94235925 0.86964688 0.83966006 0.88196959]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.91920252 0.79694323 0.80239521 0.79120879]

R2

### Testing 3 brackets of Income (0-30k, 30k-60k, 61k+)

In [59]:
print(y_allcities[y_allcities < 30000].shape)
print(y_allcities[(y_allcities >= 30000) & (y_allcities < 60000)].shape)
print(y_allcities[y_allcities >= 60000].shape)

(8120,)
(2182,)
(824,)


In [45]:
## Creating column y_train_class3

y_train = y_allcities

y_train_class3 = pd.Series(['NaN' for i in range(len(y_train)) ])

## Creating y_train for classification

brackets ={'$0-$30.99k': 0,'$31-$60.99k':1, '$61+k':3}

for index, value in enumerate(y_train):
    if y_train.iloc[index] < 31000:
        y_train_class3.iloc[index] = brackets['$0-$30.99k']
    elif y_train.iloc[index] < 61000:
        y_train_class3.iloc[index] = brackets['$31-$60.99k']
    elif y_train.iloc[index] >= 61000:
        y_train_class3.iloc[index] = brackets['$61+k']
    else:
        y_train_class3.iloc[index] = np.nan

In [46]:
# Also with stratifying on income
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class3, 
                                                    test_size=.15, random_state=42,
                                                   stratify=y_train_class3) 
X_train.shape

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [48]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

# knn_class_pca = KNeighborsClassifier()
# knn_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

adaboost_class_pca = AdaBoostClassifier()
adaboost_class_pca.fit(Z_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [26]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca, 
              adaboost_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.8705720630221
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.8579988016776513
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92443411 0.65917843 0.76085106]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92110377 0.62611807 0.69902913]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9405731204398858
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.9185140802875974
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.9671062  0.85779685 0.87585682]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.95683453 0.7960199  0.82403433]

R2 scores for <class 'sklearn.ensemble.bagging.Ba

In [54]:
for model in [logreg_class_pca, bagged_class_pca, random_forest_class_pca, 
              adaboost_class_pca] : # knn_class_pca
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)
# with f1_score set to average=samples instead of None

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.8701490959077932
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.8609946075494308
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.9247062  0.65199094 0.76534903]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92229992 0.63176895 0.71428571]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train set: 0.9874167283493709
R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> test set: 0.9197124026363092
The training accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.99181436 0.97171946 0.98269375]
The testing accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.95689996 0.78974359 0.83928571]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.988579

In [50]:
naivebayes_pca = MultinomialNB()
naivebayes_pca.fit(X_train, y_train)
accuracy_scorer(naivebayes_pca, X_train, X_test, y_train, y_test);

R2 scores for <class 'sklearn.naive_bayes.MultinomialNB'> train set: 0.6291635825314582
R2 scores for <class 'sklearn.naive_bayes.MultinomialNB'> test set: 0.609946075494308
The training accuracy-score for <class 'sklearn.naive_bayes.MultinomialNB'> is: 
0.5476778755617402
The testing accuracy-score for <class 'sklearn.naive_bayes.MultinomialNB'> is: 
0.5188460381031467



In [55]:
y_pred_rf = random_forest_class_pca.predict(Z_train)
print(confusion_matrix(y_train, y_pred_rf))
print()
y_pred_rf = random_forest_class_pca.predict(Z_test)
print(confusion_matrix(y_test, y_pred_rf))

[[6967    5    1]
 [  78 1730    0]
 [  20    4  652]]

[[1215   15    1]
 [  90  218   11]
 [   8   17   94]]


In [58]:
y_pred_bag = bagged_class_pca.predict(Z_train)
print(confusion_matrix(y_train, y_pred_bag))
print()
y_pred_bag = bagged_class_pca.predict(Z_test)
print(confusion_matrix(y_test, y_pred_bag))

[[6967    6    0]
 [  90 1718    0]
 [  19    4  653]]

[[1210   20    1]
 [  78  231   10]
 [  10   15   94]]


### Testing 3 brackets of Income (0-20k, 20k-50k, 51k+)

In [18]:
print(y_allcities[y_allcities < 20000].shape)
print(y_allcities[(y_allcities >= 20000) & (y_allcities < 50000)].shape)
print(y_allcities[y_allcities >= 50000].shape)

(5774,)
(4101,)
(1251,)


In [20]:
## Creating column y_train_class3

y_train = y_allcities

y_train_class3 = pd.Series(['NaN' for i in range(len(y_train)) ])

## Creating y_train for classification

brackets ={'$0-$20k': 0,'$20-$50k':1, '$50+k':3}

for index, value in enumerate(y_train):
    if y_train.iloc[index] < 20000:
        y_train_class3.iloc[index] = brackets['$0-$20k']
    elif y_train.iloc[index] < 50000:
        y_train_class3.iloc[index] = brackets['$20-$50k']
    elif y_train.iloc[index] >= 50000:
        y_train_class3.iloc[index] = brackets['$50+k']
    else:
        y_train_class3.iloc[index] = np.nan

In [21]:
# Also with stratifying on income
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class3, 
                                                    test_size=.15, random_state=42,
                                                   stratify=y_train_class3) 
X_train.shape

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [34]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

adaboost_class_pca = AdaBoostClassifier()
adaboost_class_pca.fit(Z_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [22]:
random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

y_pred_rf = random_forest_class_pca.predict(Z_test)
confusion_matrix(y_test, y_pred_rf)

array([[833,  29,   4],
       [100, 506,   9],
       [ 19,  23, 146]], dtype=int64)

In [36]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca, 
              adaboost_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7758274294173628
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7495506291192331
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: [0.83234531 0.68824749 0.7428262 ]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: [0.81837161 0.64845173 0.68518519]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9212223749603469
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.89035350509287
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: [0.9429083  0.8993943  0.88761358]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: [0.92359551 0.86218487 0.82065217]

R2 scores for <class 'sklearn.ensemble.bagging.Baggi

In [87]:
joblib.dump(knn_class_pca, 'knn_pca_0-20k-50k+.joblib', compress=9)

['knn_pca_0-20k-50k+.joblib']

In [ ]:
joblib.dump(random_forest_class_pca, 'rf_pca_0-20k-50k+.joblib', compress=9)

In [ ]:
joblib.dump(logreg_class_pca, 'log_pca_0-20k-50k+.joblib', compress=9)