In [1]:
%run imports_and_functions.ipynb

C:\Users\Jason\AppData\Local\conda\conda\envs\DSI-6\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Constructing All 1st Cities Dataset (Charlotte, Las Vegas, Phoenix, Pittsburgh)

In [2]:
X1 = joblib.load('X_trainCharlotteUpdated.joblib')
X2 = joblib.load('X_trainLasVegasUpdated.joblib')
X3 = joblib.load('X_trainPhoenixUpdated.joblib')
X4 = joblib.load('X_trainPittsburghUpdated.joblib')

In [3]:
print(X1.shape, X2.shape, X3.shape, X4.shape)

(3131, 1482) (2713, 1482) (4401, 1482) (3297, 1482)


In [4]:
blocks = pd.read_csv('PhoenixTrainRowCoords.csv', sep=';', compression='gzip')
blocks.shape

(4401, 11)

In [5]:
y3 = blocks['income']

In [6]:
y1 = joblib.load('y_trainCharlotteUpdated.joblib')
y2 = joblib.load('y_trainLasVegasUpdated.joblib')
y4 = joblib.load('y_trainPittsburgh.joblib')

In [7]:
print(y1.shape, y2.shape, y3.shape, y4.shape)

(3131,) (2713,) (4401,) (3297,)


In [8]:
X_allcities = X1.append(X2).append(X3).append(X4)
X_allcities.shape

(13542, 1482)

In [9]:
# Old 1st cities length is 9502
y_allcities = y1.append(y2).append(y3).append(y4)
y_allcities.shape

(13542,)

In [10]:
X_allcities.index = y_allcities.index
X_allcities.head()

landarea  waterarea  0_restaurants_near  0_restaurants_far  \
3.711900e+14         0          0                  36                101   
3.711900e+14         0          0                  98                 42   
3.711900e+14         0          0                  95                 45   
3.711900e+14         0          0                  48                 92   
3.711900e+14         0          0                  52                 88   

              1_restaurants_near  1_restaurants_far  2_restaurants_near  \
3.711900e+14                  28                142                   8   
3.711900e+14                  72                 99                  32   
3.711900e+14                  71                 99                  25   
3.711900e+14                  58                 96                  24   
3.711900e+14                  63                 92                  25   

              2_restaurants_far  3_restaurants_near  3_restaurants_far  \
3.711900e+14                 93                   0                 14   
3.711900e+14                 71                   6                  9   
3.711900e+14                 77                   6                  9   
3.711900e+14                 76                   3                 11   
3.711900e+14                 76                   5                 10   

              4_restaurants_near  4_restaurants_far  0_shopping_near  \
3.711900e+14                   0                  3               40   
3.711900e+14                   0                  3              119   
3.711900e+14                   0                  3              119   
3.711900e+14                   0                  3               43   
3.711900e+14                   0                  3               44   

              0_shopping_far  1_shopping_near  1_shopping_far  \
3.711900e+14             125                1              21   
3.711900e+14              47                1              21   
3.711900e+14              48                1              21   
3.711900e+14             124                0              14   
3.711900e+14             124                0              14   

              2_shopping_near  2_shopping_far  3_shopping_near  \
3.711900e+14                2              44                1   
3.711900e+14                2              44                6   
3.711900e+14                2              45                5   
3.711900e+14                2              36                1   
3.711900e+14                2              37                5   

              3_shopping_far  4_shopping_near  4_shopping_far  0_food_near  \
3.711900e+14              17                0               3           53   
3.711900e+14              12                1               2          173   
3.711900e+14              13                1               2          173   
3.711900e+14               9                0               3           58   
3.711900e+14               5                1               3           58   

              0_food_far  1_food_near  1_food_far  2_food_near  2_food_far  \
3.711900e+14         151           43          88            5         100   
3.711900e+14          31           55          76           54          51   
3.711900e+14          32           55          78           54          50   
3.711900e+14         142           44          66           11          79   
3.711900e+14         143           51          61           11          78   

              3_food_near  3_food_far  4_food_near  4_food_far  \
3.711900e+14            0           2            0           0   
3.711900e+14            1           1            0           0   
3.711900e+14            1           2            0           0   
3.711900e+14            1           2            0           0   
3.711900e+14            1           2            0           0   

              0_beautysvc_near  0_beautysvc_far  1_beautysvc_near  \
3.711900e+14                19      

In [11]:
X_allcities.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 13542 entries, 371190001001000.0 to 1.5420039822001016e+16
Columns: 1482 entries, landarea to 4_physicaltherapy_far
dtypes: uint16(1482)
memory usage: 38.4 MB


In [12]:
rowstodrop = y_allcities[y_allcities.astype(str) == '-'].index

In [13]:
print(y_allcities.shape)
y_allcities.drop(rowstodrop, axis=0, inplace=True)
y_allcities.shape

(13542,)


(13526,)

In [14]:
print(X_allcities.shape)
X_allcities.drop(rowstodrop, axis=0, inplace=True)
X_allcities.shape

(13542, 1482)


(13526, 1482)

In [15]:
nantodrop = y_allcities[y_allcities.isnull()].index
print(y_allcities.shape)
y_allcities.drop(nantodrop, axis=0, inplace=True)
y_allcities.shape

(13526,)


(13499,)

In [16]:
print(X_allcities.shape)
X_allcities.drop(nantodrop, axis=0, inplace=True)
X_allcities.shape

(13526, 1482)


(13499, 1482)

In [17]:
nantodrop = y_allcities[y_allcities.isna()].index
nantodrop

Float64Index([], dtype='float64')

In [18]:
y_allcities = y_allcities.map(float)

y_allcities.head()

3.711900e+14    107319.0
3.711900e+14    107319.0
3.711900e+14    107319.0
3.711900e+14    107319.0
3.711900e+14    107319.0
Name: income, dtype: float64

In [42]:
joblib.dump(X_allcities, 'Xtrain_1stcities_2019.joblib', compress=9)

['Xtrain_1stcities_2019.joblib']

In [43]:
joblib.dump(y_allcities, 'ytrain_1stcities_2019.joblib', compress=9)

['ytrain_1stcities_2019.joblib']

## Testing Varied ML Models on All Cities Dataset

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, AdaBoostRegressor, RandomForestRegressor, BaggingClassifier
from sklearn.svm import SVR
from sklearn.metrics import f1_score, mean_squared_error

In [20]:
X_features = joblib.load('X_features.joblib')

In [32]:
def accuracy_scorer(model, X_train, X_test, y_train, y_test):
    
    y_pred = pd.Series(data=model.predict(X_train),dtype=int)
    accuracy_train = f1_score(y_true = y_train,
                        y_pred = y_pred, average=None)
    
    y_pred = pd.Series(data=model.predict(X_test),dtype=int)
    accuracy_test = f1_score(y_true = y_test,
                       y_pred = y_pred, average=None)
    
    r2_scores = (model.score(X_train, y_train), model.score(X_test, y_test))
    
    print("R2 scores for " + str(type(model)) + " train set: " + str(r2_scores[0]))
    print("R2 scores for " + str(type(model)) + " test set: " + str(r2_scores[1]))
    print("The training accuracy-score for " + str(type(model)) + " is: ")
    print(str(accuracy_train))
    print("The testing accuracy-score for " + str(type(model)) + " is: ")
    print(str(accuracy_test))
    print()
    return (accuracy_train, accuracy_test)

### Comparing 2019 Trained Models Scores for 2nd Cities Datasets to 2014 Kaggle Trained 1st Cities Models 

In [19]:
X1 = joblib.load('./2nd_citiesFinalsets/X_trainBoston.joblib')
X2 = joblib.load('./2nd_citiesFinalsets/X_trainMiami.joblib')
X3 = joblib.load('./2nd_citiesFinalsets/X_trainSeattle.joblib')
print(X1.shape, X2.shape, X3.shape)

(2400, 1482) (4355, 1482) (2747, 1482)


In [20]:
y1 = joblib.load('./2nd_citiesFinalsets/y_trainBoston.joblib')
y2 = joblib.load('./2nd_citiesFinalsets/y_trainMiami.joblib')
y3 = joblib.load('./2nd_citiesFinalsets/y_trainSeattle.joblib')
print(y1.shape, y2.shape, y3.shape)

(2400,) (4355,) (2747,)


In [21]:
Xtrain_2nd_cities = joblib.load('./2nd_citiesFinalsets/Xtrain_2nd_cities.joblib')
ytrain_2nd_cities = joblib.load('./2nd_citiesFinalsets/ytrain_2nd_cities.joblib')
print(Xtrain_2nd_cities.shape, ytrain_2nd_cities.shape)

(9502, 1482) (9502,)


In [34]:
ytrain_2nd_cities.value_counts()

14914.0     44
12533.0     43
11878.0     41
24508.0     39
14459.0     38
8383.0      38
8573.0      37
7965.0      36
14208.0     36
86364.0     36
84438.0     36
18861.0     36
13876.0     35
14783.0     35
13827.0     34
28463.0     33
7459.0      33
46853.0     33
13567.0     33
36434.0     33
14357.0     32
19157.0     32
14631.0     32
15237.0     32
11851.0     32
75025.0     32
53984.0     31
11535.0     31
15772.0     31
22333.0     31
31908.0     30
12828.0     30
72854.0     30
13973.0     30
13264.0     30
17376.0     30
30957.0     30
12535.0     30
81966.0     29
37625.0     29
71597.0     29
17704.0     28
5958.0      28
12592.0     28
17897.0     28
20261.0     28
12134.0     28
16838.0     28
23042.0     28
20117.0     28
9710.0      28
19004.0     27
17200.0     27
78089.0     27
32085.0     27
12258.0     27
16671.0     27
15652.0     27
35636.0     27
47316.0     27
24873.0     27
14929.0     27
15932.0     27
13428.0     27
33877.0     26
55082.0     26
16129.0   

In [35]:
# Scaler and pca transform already fit with 2014 Kaggle X_train
X_test_scaled0 = ss.transform(Xtrain_2nd_cities)
X_test_scaled3 = ss.transform(X3)

Z_test0 = pca.transform(X_test_scaled0)
Z_test3 = pca.transform(X_test_scaled3)

In [62]:
# Models below already trained with 2014 Kaggle X_train and 7 brackets of income
for model in [logreg_class_pca, random_forest_class_pca, cart_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_test0, Z_test3, make_8brackets(ytrain_2nd_cities), make_8brackets(y3))


R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.18848663439275942
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.11576265016381507
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.10513296 0.32686153 0.15142972 0.07467753 0.1469712  0.02889246
 0.07142857 0.29559519]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.         0.         0.17274472 0.15050167 0.19508671 0.04733728
 0.07899461 0.13173653]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.1474426436539676
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.04004368401892974
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.11741257 0.26102224 0.15347053 0.07949527 0.03090909 0.0224359
 0.05946792 0.10621762]
The testing accuracy-score for <c

KeyboardInterrupt: 

In [63]:
X_test_scaled1 = ss.transform(X1)
X_test_scaled2 = ss.transform(X2)

Z_test1 = pca.transform(X_test_scaled1)
Z_test2 = pca.transform(X_test_scaled2)

In [64]:
for model in [logreg_class_pca, random_forest_class_pca, cart_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_test1, Z_test2, make_8brackets(y1), make_8brackets(y2))


R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.18541666666666667
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.25809414466130887
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.10212766 0.24855491 0.13071895 0.05494505 0.12837838 0.13550136
 0.         0.39338235]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.09554551 0.46872682 0.06513106 0.01960784 0.01948052 0.06716418
 0.19742489 0.06875   ]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.12166666666666667
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.23237657864523537
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.13918306 0.20869565 0.1301908  0.06419753 0.         0.
 0.01162791 0.08311688]
The testing accuracy-score for <class '

### Testing 7 brackets of Income (0-11k, 11-21k, 21-31k, 31-41k, 41-51k, 51k-61k, 61k+)

In [29]:
print(y_allcities[y_allcities < 11000].shape)
print(y_allcities[(y_allcities >= 11000) & (y_allcities < 21000)].shape)
print(y_allcities[(y_allcities >= 21000) & (y_allcities < 31000)].shape)
print(y_allcities[(y_allcities >= 31000) & (y_allcities < 41000)].shape)
print(y_allcities[(y_allcities >= 41000) & (y_allcities < 51000)].shape)
print(y_allcities[(y_allcities >= 51000) & (y_allcities < 61000)].shape)
print(y_allcities[y_allcities >= 61000].shape)

(4773,)
(2979,)
(2546,)
(1168,)
(665,)
(456,)
(912,)


In [52]:
## Creating column y_train_class

y_train = y_allcities

def make_8brackets(y_train) :
    y_train_class = pd.Series(['NaN' for i in range(len(y_train)) ])

    ## Creating y_train for classification

    brackets ={'$0-$10.99k': 0,'$11-$20.99k':1, '$21-$30.99k':2, '$31-$40.99k':3, '$41-$50.99k':4, 
               '$51-$60.99k':5,'$61-$70.99k':6, '$71+k':7}

    for index, value in enumerate(y_train):
        if y_train.iloc[index] < 11000:
            y_train_class.iloc[index] = brackets['$0-$10.99k']
        elif y_train.iloc[index] < 21000:
            y_train_class.iloc[index] = brackets['$11-$20.99k']
        elif y_train.iloc[index] < 31000:
            y_train_class.iloc[index] = brackets['$21-$30.99k']
        elif y_train.iloc[index] < 41000:
            y_train_class.iloc[index] = brackets['$31-$40.99k']   
        elif y_train.iloc[index] < 51000:
            y_train_class.iloc[index] = brackets['$41-$50.99k']
        elif y_train.iloc[index] < 61000:
            y_train_class.iloc[index] = brackets['$51-$60.99k']
        elif y_train.iloc[index] < 71000:
            y_train_class.iloc[index] = brackets['$61-$70.99k']   
        elif y_train.iloc[index] >= 71000:
            y_train_class.iloc[index] = brackets['$71+k']
        else:
            y_train_class.iloc[index] = np.nan
    return y_train_class

In [53]:
y_train_class = make_8brackets(y_train)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class, 
                                                    test_size=.15, random_state=42) 
X_train.shape

(11474, 1482)

In [55]:

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [56]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [57]:
knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [58]:
cart_class_pca = DecisionTreeClassifier()
cart_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [59]:
random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [28]:
adaboost_class_pca = AdaBoostClassifier()
adaboost_class_pca.fit(Z_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [55]:
for model in [logreg_class_pca, random_forest_class_pca, adaboost_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)
# AdaBoost is the worst classifier among those tested, with default parameters, and
# with this level of income brackets

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7591947010632735
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7333333333333333
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.90846736 0.70390456 0.63152851 0.57967529 0.66272189 0.77097506
 0.79676441 0.65880039]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.90296496 0.66798419 0.56971514 0.55483871 0.61068702 0.64615385
 0.86255924 0.57647059]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.9816977514380338
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.8755555555555555
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.99592542 0.96381832 0.97611871 0.97828335 0.99222798 0.99790356
 0.98661568 0.97029703]
The testing accuracy-score for <cla

In [60]:
for model in [cart_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> train set: 0.9856196618441694
R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> test set: 0.8261728395061728
The training accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.99727992 0.96823869 0.9809568  0.98712004 0.980322   0.99870968
 1.         0.98758357]
The testing accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.93828892 0.83160083 0.7628866  0.6630137  0.68393782 0.70588235
 0.63492063 0.79646018]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train set: 0.980826215792226
R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> test set: 0.8760493827160494
The training accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.99592341 0.96495957 0.97609654 0.97375193 0.96872207 0.99483204
 0.98319328 0.97687861]
The testing accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifie

In [32]:
# Models run with 2014 Kaggle X_train
for model in [cart_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> train set: 1.0
R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> test set: 0.8660589060308556
The training accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[1. 1. 1. 1. 1. 1. 1. 1.]
The testing accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.89056604 0.93756614 0.85492228 0.79710145 0.74820144 0.7826087
 0.89130435 0.76816609]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train set: 0.9949232293214463
R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> test set: 0.8962131837307152
The training accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.99746407 0.99733901 0.99350046 0.98845893 0.99448732 0.99595142
 0.99317251 0.99442033]
The testing accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.90980392 0.94409938 0.89405685 0.81318681 0.77464789 0.86813187
 0.9

In [33]:
joblib.dump(logreg_class_pca, 'log_pca_8brackets.joblib', compress=9)

joblib.dump(random_forest_class_pca, 'rf_pca_8brackets.joblib', compress=9)

['log_pca_8brackets.joblib']

### Testing 4 brackets of Income (0-20k, 20-40k, 40k-60k, 61k+)

In [59]:
print(y_allcities[y_allcities < 20000].shape)
print(y_allcities[(y_allcities >= 20000) & (y_allcities < 40000)].shape)
print(y_allcities[(y_allcities >= 40000) & (y_allcities < 60000)].shape)
print(y_allcities[y_allcities >= 60000].shape)

(7410,)
(3998,)
(1148,)
(943,)


In [26]:
## Creating column y_train_class2

y_train = y_allcities

def make_4brackets(y_train) :

    y_train_class2 = pd.Series(['NaN' for i in range(len(y_train)) ])

    ## Creating y_train for classification

    brackets ={'$0-$20.99k': 0,'$21-$40.99k':1, '$41-$60.99k':2, '$61+k':3}

    for index, value in enumerate(y_train):
        if y_train.iloc[index] < 21000:
            y_train_class2.iloc[index] = brackets['$0-$20.99k']
        elif y_train.iloc[index] < 41000:
            y_train_class2.iloc[index] = brackets['$21-$40.99k']
        elif y_train.iloc[index] < 61000:
            y_train_class2.iloc[index] = brackets['$41-$60.99k']
        elif y_train.iloc[index] >= 61000:
            y_train_class2.iloc[index] = brackets['$61+k']
        else:
            y_train_class2.iloc[index] = np.nan
    
    return y_train_class2

In [67]:
y_train_class2 = make_4brackets(y_train)

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class2, 
                                                    test_size=.15, random_state=42) 
X_train.shape

(11474, 1482)

In [69]:
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [30]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [70]:
knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [71]:
# With 2019 1st Cities Dataset
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7844692347917029
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7822222222222223
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.85875229 0.64377832 0.64171779 0.77358491]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.86005488 0.61211477 0.61016949 0.82889734]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9265295450583929
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.8923456790123456
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.95907419 0.89364303 0.84499462 0.88785047]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.93917482 0.82998172 0.79279279 0.86029412]

R2

In [64]:
# With 2014 Kaggle Dataset
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7839463134042183
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7812345679012346
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.85788476 0.63694268 0.65669856 0.77672727]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.8583691  0.60108108 0.63545151 0.82889734]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9283597699145895
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.8888888888888888
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.95953757 0.89756253 0.84017279 0.88918558]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.93517357 0.82509506 0.78443114 0.85714286]

R2

In [72]:
# Scaler and pca transform already fit with 2014 Kaggle X_train
X_test_scaled0 = ss.transform(Xtrain_2nd_cities)
X_test_scaled3 = ss.transform(X3)

Z_test0 = pca.transform(X_test_scaled0)
Z_test3 = pca.transform(X_test_scaled3)

In [73]:
# Models below already trained with 2014 Kaggle X_train and 7 brackets of income
for model in [logreg_class_pca, random_forest_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_test0, Z_test3, make_4brackets(ytrain_2nd_cities), make_4brackets(y3))


R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.36434434855819825
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.1488896978522024
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.50082663 0.18214826 0.17015819 0.32190343]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.03975704 0.25378347 0.19174434 0.18154312]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.3779204378025679
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.10556971241354204
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.56383749 0.23706378 0.06562848 0.16804083]
The testing accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.02275449 0.2366782  0.07592752 0.09180328]



C:\Users\Jason\AppData\Local\conda\conda\envs\DSI-6\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Jason\AppData\Local\conda\conda\envs\DSI-6\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> train set: 0.20953483477162702
R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> test set: 0.15835456862031308
The training accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.36431691 0.16623377 0.15948963 0.18060837 0.         0.
 0.         0.        ]
The testing accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.01733478 0.17826618 0.24242424 0.24895105 0.         0.
 0.         0.        ]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train set: 0.3886550199957904
R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> test set: 0.14051692755733527
The training accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.56000848 0.2995015  0.08054393 0.16937618]
The testing accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.04801097 0.24666243 0.09437086 0.15936255]

R

In [74]:
X_test_scaled1 = ss.transform(X1)
X_test_scaled2 = ss.transform(X2)

Z_test1 = pca.transform(X_test_scaled1)
Z_test2 = pca.transform(X_test_scaled2)

In [75]:
for model in [logreg_class_pca, random_forest_class_pca, cart_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_test1, Z_test2, make_4brackets(y1), make_4brackets(y2))


R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.42625
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.4661308840413318
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.37873357 0.25508318 0.22175732 0.65772669]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.68682892 0.07917889 0.01114206 0.07862759]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.32375
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.5795637198622273
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.45454545 0.25701239 0.0668693  0.26577438]
The testing accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.74554083 0.22211155 0.02580645 0.13523132]



C:\Users\Jason\AppData\Local\conda\conda\envs\DSI-6\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Jason\AppData\Local\conda\conda\envs\DSI-6\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> train set: 0.17916666666666667
R2 scores for <class 'sklearn.tree.tree.DecisionTreeClassifier'> test set: 0.25855338691159585
The training accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.3250215  0.16591928 0.15620999 0.19757689 0.         0.
 0.         0.        ]
The testing accuracy-score for <class 'sklearn.tree.tree.DecisionTreeClassifier'> is: 
[0.44891355 0.16077537 0.02882483 0.00306279 0.         0.
 0.         0.        ]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train set: 0.28708333333333336
R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> test set: 0.6011481056257175
The training accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.35430297 0.32916973 0.00540541 0.20702403]
The testing accuracy-score for <class 'sklearn.ensemble.bagging.BaggingClassifier'> is: 
[0.75296476 0.32003844 0.11377246 0.07792208]

R

In [78]:
y_pred_bag = bagged_class_pca.predict(Z_test0)
print(confusion_matrix(make_4brackets(ytrain_2nd_cities), y_pred_bag) / len(y_pred_bag))
print()
y_pred_bag = bagged_class_pca.predict(Z_test2)
print(confusion_matrix(make_4brackets(y2), y_pred_bag)  / len(y_pred_bag))

[[0.27794149 0.11229215 0.01357609 0.01715428]
 [0.10839823 0.07903599 0.01136603 0.02799411]
 [0.08408756 0.05041044 0.00810356 0.01220796]
 [0.10124184 0.05925068 0.01336561 0.02357398]]

[[0.51756602 0.17956372 0.01354765 0.02411022]
 [0.09299656 0.07646383 0.00895522 0.02250287]
 [0.02801378 0.01056257 0.0043628  0.00619977]
 [0.00137773 0.01033295 0.00068886 0.00275545]]


In [79]:
y_pred_bag = random_forest_class_pca.predict(Z_test0)
print(confusion_matrix(make_4brackets(ytrain_2nd_cities), y_pred_bag) / len(y_pred_bag))
print()
y_pred_bag = random_forest_class_pca.predict(Z_test2)
print(confusion_matrix(make_4brackets(y2), y_pred_bag) / len(y_pred_bag))

[[0.28699221 0.11534414 0.00557777 0.01304988]
 [0.12881499 0.06219743 0.0128394  0.02294254]
 [0.09261208 0.0438855  0.00620922 0.01210272]
 [0.08861292 0.07651021 0.00978741 0.02252157]]

[[0.52307692 0.1836969  0.00964409 0.01836969]
 [0.11595867 0.05120551 0.01079219 0.02296211]
 [0.02525832 0.01928817 0.00091848 0.00367394]
 [0.00413318 0.00597015 0.00068886 0.0043628 ]]


### Testing of 6 Cities X_train, 4 brackets of Income on Last City: Miami

In [23]:
X_allcities = X_allcities.append(X1).append(X3)
X_allcities.shape

(18646, 1482)

In [37]:
y_allcities = y_allcities.append(y1).append(y3)
y_allcities.shape

(23793,)

In [27]:
y_train_class3 = make_4brackets(y_allcities)

In [28]:
make_4brackets(y2).shape

(4355,)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class3, 
                                                    test_size=.15, random_state=42) 

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [41]:
y_train_class3.shape

(18646,)

In [40]:
accuracy_scorer(logreg_class_pca, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7030096536059057
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.6914551304969611
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.79217864 0.54782489 0.52730109 0.74614306]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.79413681 0.50488599 0.5035461  0.71857923]



(array([0.79217864, 0.54782489, 0.52730109, 0.74614306]),
 array([0.79413681, 0.50488599, 0.5035461 , 0.71857923]))

In [43]:
joblib.dump(ss, '4brackets_StandardScaler.joblib', compress=9)
joblib.dump(pca, '4brackets_PCA.joblib', compress=9)

['4brackets_PCA.joblib']

In [42]:
joblib.dump(logreg_class_pca, 'mediocre_logistic_4brackets.joblib', compress=9)

['mediocre_logistic_4brackets.joblib']

In [ ]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

In [84]:
knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [86]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.699917975897533
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.6893099749731856
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.79493701 0.53593514 0.52009895 0.73925234]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.79648323 0.49301561 0.48601399 0.72479564]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9200580478263612
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.8823739721129782
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.95070614 0.89021765 0.86698043 0.92277401]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.93318318 0.84195997 0.7826087  0.87231353]

R2 

In [87]:
# Scaler and pca transform already fit with 2014 Kaggle X_train
X_test_scaled0 = ss.transform(Xtrain_2nd_cities)
X_test_scaled2 = ss.transform(X2)

Z_test0 = pca.transform(X_test_scaled0)
Z_test2 = pca.transform(X_test_scaled2)

In [88]:
for model in [logreg_class_pca, random_forest_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_test0, Z_test2, make_4brackets(ytrain_2nd_cities), make_4brackets(y2))


R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.6442854135971374
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.5412169919632607
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.72422486 0.49401579 0.57536286 0.67594255]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.73228737 0.1036036  0.09324009 0.11409396]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.7323721321826984
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.43283582089552236
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.6898442  0.63751051 0.83008731 0.83725219]
The testing accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.60003757 0.22619048 0.04175365 0.08563536]

R2 scores for <class 'sklearn

In [26]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.8705720630221
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.8579988016776513
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92443411 0.65917843 0.76085106]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.92110377 0.62611807 0.69902913]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9405731204398858
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.9185140802875974
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.9671062  0.85779685 0.87585682]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.95683453 0.7960199  0.82403433]

R2 scores for <class 'sklearn.ensemble.bagging.Ba

### Final Testing Using 6 City X_train with 3 brackets of Income (0-20k, 20k-50k, 51k+) on Last City: Miami

In [22]:
print(y_allcities[y_allcities < 20000].shape)
print(y_allcities[(y_allcities >= 20000) & (y_allcities < 50000)].shape)
print(y_allcities[y_allcities >= 50000].shape)

(7410,)
(4684,)
(1405,)


In [93]:
## Creating column y_train_class3

y_train = y_allcities

def make_3brackets(y_train) :

    y_train_class3 = pd.Series(['NaN' for i in range(len(y_train)) ])

    ## Creating y_train for classification

    brackets ={'$0-$20k': 0,'$20-$50k':1, '$50+k':2}

    for index, value in enumerate(y_train):
        if y_train.iloc[index] < 20000:
            y_train_class3.iloc[index] = brackets['$0-$20k']
        elif y_train.iloc[index] < 50000:
            y_train_class3.iloc[index] = brackets['$20-$50k']
        elif y_train.iloc[index] >= 50000:
            y_train_class3.iloc[index] = brackets['$50+k']
        else:
            y_train_class3.iloc[index] = np.nan
            
    return y_train_class3

In [94]:
y_train_class4 = make_3brackets(y_train)

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X_allcities, y_train_class4, 
                                                    test_size=.15, random_state=42) 

ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

## Applying PCA to Xs
pca = PCA(n_components=200)
pca = pca.fit(X_train_scaled)
Z_train = pca.transform(X_train_scaled)
Z_test =pca.transform(X_test_scaled)

In [96]:
logreg_class_pca = LogisticRegression()
logreg_class_pca.fit(Z_train, y_train)

knn_class_pca = KNeighborsClassifier()
knn_class_pca.fit(Z_train, y_train)

bagged_class_pca = BaggingClassifier()
bagged_class_pca.fit(Z_train, y_train)

random_forest_class_pca = RandomForestClassifier()
random_forest_class_pca.fit(Z_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [97]:
for model in [logreg_class_pca, knn_class_pca, bagged_class_pca, random_forest_class_pca] :
    accuracy_scorer(model, Z_train, Z_test, y_train, y_test)

R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.7357561991292826
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.7247050411154808
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.78350384 0.65131579 0.757777  ]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.78128323 0.62422535 0.74348697]

R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> train set: 0.9363997728563316
R2 scores for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> test set: 0.9095459420808009
The training accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.95148267 0.919898   0.93270142]
The testing accuracy-score for <class 'sklearn.neighbors.classification.KNeighborsClassifier'> is: 
[0.93591772 0.88346056 0.8955495 ]

R2 scores for <class 'sklearn.ensemble.bagging

In [98]:
X_test_scaled0 = ss.transform(Xtrain_2nd_cities)
X_test_scaled2 = ss.transform(X2)

Z_test0 = pca.transform(X_test_scaled0)
Z_test2 = pca.transform(X_test_scaled2)

In [100]:
for model in [logreg_class_pca, random_forest_class_pca, bagged_class_pca, knn_class_pca] :
    accuracy_scorer(model, Z_test0, Z_test2, make_3brackets(ytrain_2nd_cities), make_3brackets(y2))


R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> train set: 0.6545990317827826
R2 scores for <class 'sklearn.linear_model.logistic.LogisticRegression'> test set: 0.46498277841561425
The training accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.64839927 0.5728972  0.7593445 ]
The testing accuracy-score for <class 'sklearn.linear_model.logistic.LogisticRegression'> is: 
[0.63501805 0.1825226  0.12750885]

R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> train set: 0.717006945906125
R2 scores for <class 'sklearn.ensemble.forest.RandomForestClassifier'> test set: 0.39196326061997705
The training accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.61838352 0.6907387  0.86649503]
The testing accuracy-score for <class 'sklearn.ensemble.forest.RandomForestClassifier'> is: 
[0.50782537 0.28709677 0.07692308]

R2 scores for <class 'sklearn.ensemble.bagging.BaggingClassifier'> train 

In [107]:
y_pred_bag = logreg_class_pca.predict(Z_test0)
print(list(map(np.ceil, 
          confusion_matrix(make_3brackets(ytrain_2nd_cities), y_pred_bag) / len(y_pred_bag) * 100)))
print()
y_pred_bag = logreg_class_pca.predict(Z_test2)
print(list(map(np.ceil, 
          confusion_matrix(make_3brackets(y2), y_pred_bag) / len(y_pred_bag) * 100)))

[array([25., 11.,  5.]), array([10., 20.,  6.]), array([ 2.,  3., 22.])]

[array([41., 21.,  9.]), array([16.,  5.,  7.]), array([1., 1., 2.])]


In [106]:
y_pred_bag = knn_class_pca.predict(Z_test0)
print(list(map(np.ceil, 
          confusion_matrix(make_3brackets(ytrain_2nd_cities), y_pred_bag) / len(y_pred_bag) * 100)))
print()
y_pred_bag = knn_class_pca.predict(Z_test2)
print(list(map(np.ceil, 
          confusion_matrix(make_3brackets(y2), y_pred_bag) / len(y_pred_bag) * 100)))

[array([23., 14.,  4.]), array([ 9., 24.,  3.]), array([ 1.,  1., 25.])]

[array([34., 30.,  7.]), array([18.,  7.,  4.]), array([2., 1., 1.])]
